
version: 2

sources:
  - name: HOCKEYDB
    description: 'RAW DATA FROM HOCKEY DB'
    database: HOCKEYDB
    schema: HOCKEY
    tables:
      - name: ABBREV
        description: 'table contains the hockey team abbreviations'
        columns:
          - name: TYPE
            description: 'type of abbreviation'
          - name: CODE
            description: 'Abbreviation code'
          - name : fullname
            description: 'full name of team'
      - name: AWARDSCOACHES
        description: 'contains coaches info'