
version: 2
<<<<<<< HEAD

=======
<<<<<<< HEAD

=======
sources:
  - name: HOCKEYDB
    description: 'RAW DATA FROM HOCKEY DB'
    database: HOCKEYDB
    schema: HOCKEY
    tables:
      - name: ABBREV
        description: 'table contains the hockey team abbreviations'
        columns:
          - name: TYPE
            description: 'type of abbreviation'
          - name: CODE
            description: 'Abbreviation code'
          - name : fullname
            description: 'full name of team'














>>>>>>> 561ffc99453a3fe28e1ef3e5637b605e66fe4058
>>>>>>> f7e31b89df9bf9e60e0c4b967763491840119062
>>>>>>> 173aa4318ccbf3e17c208d9591178520f392c47f
>>>>>>> b5a39cf4394cb6ac9c9ea0a3ea92124d9ad1f297
>>>>>>> b3ef7c5ee44c195f46a194489a4ec63bde47366b
>>>>>>> 51a4469e6c5cbc654c708e66eb163985f8fe7a63
models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD

>>>>>>> 173aa4318ccbf3e17c208d9591178520f392c47f
>>>>>>> b3ef7c5ee44c195f46a194489a4ec63bde47366b
sources:
  - name: HOCKEYDB
    description: 'RAW DATA FROM HOCKEY DB'
    database: HOCKEYDB
    schema: HOCKEY
    tables:
      - name: ABBREV
        description: 'table contains the hockey team abbreviations'
        columns:
          - name: TYPE
            description: 'type of abbreviation'
          - name: CODE
            description: 'Abbreviation code'
          - name : fullname
<<<<<<< HEAD
            description: 'full name of team'
=======
<<<<<<< HEAD
            description: 'full name of team'
=======
            description: 'full name of team'
=======
>>>>>>> f7e31b89df9bf9e60e0c4b967763491840119062
>>>>>>> 173aa4318ccbf3e17c208d9591178520f392c47f
>>>>>>> b5a39cf4394cb6ac9c9ea0a3ea92124d9ad1f297
>>>>>>> b3ef7c5ee44c195f46a194489a4ec63bde47366b
>>>>>>> 51a4469e6c5cbc654c708e66eb163985f8fe7a63
